### ISSUE TITLE
What differentiates from node "config"  module? 

### ISSUE THREAD

**Issue by chadxz** [HenrikJoreteg/getconfig#11]
I have been using the npm module ["config"](https://github.com/lorenwest/node-config)  for the purpose you express in the README. Is there some problem with that module that you were trying to solve here? Just trying to understand when i may want to use this. :)

**Comment by nlf** [comment]
This module is basically just way way simpler. It doesn't support extra formats, it doesn't let you override your config with environment variables, it just `require`s files from the config directory and merges them together. That's it. If you need something more complicated, let me know and we'll see if it's worth adding.
