### ISSUE TITLE
config files naming scheme

### ISSUE THREAD

**Issue by Offirmo** [HenrikJoreteg/getconfig#13]
Your module looks awesome !

I just have troubles with the naming scheme. In a file explorer or in an IDE, files are sorted by name. It's thus common to name related files with a pattern like that «common» -> «specific», the "common" part making sure that files appears close in a file listing.

In that case, in my current company, it gives :
```
config.development.json
config.production.json
config.test.json
```

Isn't it nicer ?

**Comment by nlf** [comment]
I put them in a directory, so `config/dev.json` etc
