### ISSUE TITLE
inheriting from a global config

### ISSUE THREAD

**Issue by Offirmo** [HenrikJoreteg/getconfig#14]
It's nice to have a different configs for dev, prod, etc. But most likely those environment-specific config will share some common stuff.

So it would be nice to still load "config.«env».json" but even better to use it to extend a common "config.json"

And while we are at merging configs, in my company we have :
```
config.json  <-- global, root config, stored in github
config.development.json  <-- config adjustments for env "development", stored in github
config.development.local.json <-- final adjustments for current developper machine, NOT stored in github
```

I find it a nice scheme. What do you think ?

**Comment by nlf** [comment]
`config/default.json` is what you want now
