### ISSUE TITLE
default environment

### ISSUE THREAD

**Issue by Offirmo** [HenrikJoreteg/getconfig#15]
Hello,

using NODE_ENV is an express.js convention https://groups.google.com/forum/#!topic/nodejs/GGL-SGfWKkI

express itself will default to 'development' if not found (http://expressjs.com/api)

So I humbly suggest to change the default env value to 'development', not 'dev'

**Comment by nlf** [comment]
It'll load `dev`, `devel`, `develop`, and `development` now by default.
