### ISSUE TITLE
Wrong config dir using Phusion Passenger

### ISSUE THREAD

**Issue by berga** [HenrikJoreteg/getconfig#26]
Serving an express app with Passenger as application server 
I got the _Error: Unable to find a config directory_ 

Passenger uses an helper script to boot the app (helper-scripts/node-loader.js)
so the findConfig function detect the config path starting from require.main.filename
which is a system directory and indeed it cannot store config files.

is it possible to change the lookup part to really try to use process.cwd() if looking on the entire tree of _require.main.filename_ fails?

**Comment by nlf** [comment]
this will be in 4.0.0
