### ISSUE TITLE
Variables in not working

### ISSUE THREAD

**Issue by rickerd** [HenrikJoreteg/getconfig#32]
Using 4.4.1 and having my variables in all.json and default.json just to be sure.. The final result is not parsed correctly for some reason.

`"proxyUrl": "http://${self.hapi.host}:${self.hapi.port}"`

Results in:
`http://localhost:${self.hapi.port}`

Is there maybe a bug in the second parameter parser? Also in the docs/readme i think there's an typo.
` "url": "http://${self.host}:${self.port}`
The string is not closed with a quotation mark "

**Comment by nlf** [comment]
Good finds! Will fix today
